# Generated by Django 2.2.12 on 2021-02-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0008_destructionlistitem_extra_zaak_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlist",
            name="contains_sensitive_info",
            field=models.BooleanField(
                default=True,
                help_text="Specify whether this list contains privacy sensitive data. If set to true, the report of destruction will NOT contain case descriptions or the remarks by the archivist.",
                verbose_name="contains sensitive information",
            ),
        ),
    ]
