# Generated by Django 2.2.12 on 2021-03-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0011_remove_destructionlistreviewcomment_author"),
        ("destruction", "0009_destructionlist_contains_sensitive_info"),
    ]

    operations = []
