# Generated by Django 2.2.12 on 2021-03-09 10:11

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0012_merge_20210304_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="short_review_zaaktypes",
            field=ArrayField(
                base_field=models.URLField(
                    max_length=1000, verbose_name="cases with short review process"
                ),
                blank=True,
                default=list,
                help_text="Cases for which a second reviewer of the destruction list is optional",
                size=None,
            ),
        ),
    ]
