# Generated by Django 2.2.18 on 2021-03-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0014_auto_20210325_1334"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="standardreviewanswer",
            options={
                "ordering": ("order",),
                "verbose_name": "standard review answers",
                "verbose_name_plural": "standard review answers",
            },
        ),
        migrations.AlterField(
            model_name="standardreviewanswer",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
    ]
