# Generated by Django 2.2.24 on 2021-12-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0019_destructionlistassignee_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="case_type",
            field=models.URLField(
                blank=True,
                help_text="The case type URL to use when creating the case for the destruction list deletion.",
                verbose_name="case type",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="create_zaak",
            field=models.BooleanField(
                default=False,
                help_text="Should a case be created once a destruction list has been deleted?",
                verbose_name="create zaak",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="document_type",
            field=models.URLField(
                blank=True,
                help_text="The document type URL to use when creating the case for the destruction list deletion.",
                verbose_name="document type",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="result_type",
            field=models.URLField(
                blank=True,
                help_text="The result type URL to use when creating the case for the destruction list deletion.",
                verbose_name="result type",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="source_organisation",
            field=models.CharField(
                blank=True,
                help_text="Source organisation RSIN",
                max_length=9,
                verbose_name="source organisation",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="status_type",
            field=models.URLField(
                blank=True,
                help_text="The status type URL to use when creating the case for the destruction list deletion.",
                verbose_name="status type",
            ),
        ),
    ]
