# Generated by Django 2.2.24 on 2021-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0021_destructionlist_zaak_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="destruction_report_downloadable",
            field=models.BooleanField(
                default=True,
                help_text="Should the destruction report be downloadable through the application?",
                verbose_name="destruction report downloadable",
            ),
        ),
    ]
