# Generated by Django 2.2.26 on 2022-02-01 11:17

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0022_archiveconfig_destruction_report_downloadable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveconfig",
            name="days_until_reminder",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Number of days until an email is sent reminding that the destruction list needs to be dealt with",
                verbose_name="days until reminder",
            ),
        ),
        migrations.AlterField(
            model_name="destructionlist",
            name="contains_sensitive_info",
            field=models.BooleanField(
                default=True,
                help_text="Specify whether this destruction list contains privacy sensitive data. If set to true, the report of destruction will NOT contain case descriptions or the remarks by the archivist.",
                verbose_name="contains sensitive information",
            ),
        ),
        migrations.AlterField(
            model_name="destructionlistitem",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("suggested", "suggested for destruction"),
                    ("removed", "removed from the destruction list during review"),
                    ("processing", "is currently being destroyed"),
                    ("destroyed", "successfully destroyed"),
                    ("failed", "destruction did not succeed"),
                ],
                default="suggested",
                max_length=80,
                protected=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="destructionlistitemreview",
            name="suggestion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("remove", "remove"),
                    ("change_and_remove", "change and remove"),
                ],
                max_length=80,
                verbose_name="suggestion",
            ),
        ),
        migrations.AlterField(
            model_name="standardreviewanswer",
            name="reason",
            field=models.CharField(
                help_text="Reason for the reviewer to request changes to a destruction list.",
                max_length=200,
                verbose_name="reason",
            ),
        ),
    ]
