# Generated by Django 2.2.26 on 2022-03-22 08:24

from django.db import migrations
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0023_auto_20220201_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlistreview",
            name="additional_document",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="An additional document relevant for this destruction list. It will be related to the case created after the destruction list is processed.",
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="reviews/%Y/%m/%d",
                verbose_name="additional document",
            ),
        ),
    ]
