# Generated by Django 2.2.26 on 2022-03-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0024_destructionlistreview_additional_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="additional_review_document_type",
            field=models.URLField(
                blank=True,
                help_text="The document type URL to use for documents which were uploaded by the reviewers during the review process.",
                verbose_name="Additional review document type",
            ),
        ),
    ]
