# Generated by Django 2.2.12 on 2021-02-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themeconfig",
            name="organization_name",
            field=models.CharField(
                help_text="Shown at the top of the footer.",
                max_length=100,
                verbose_name="Organization name",
            ),
        ),
    ]
