# Generated by Django 2.2.12 on 2021-03-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_emailconfigs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailconfig", options={"verbose_name": "email configuration"},
        ),
    ]
