# Generated by Django 2.2.12 on 2021-03-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_auto_20210323_1140"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfig",
            name="from_email",
            field=models.EmailField(
                default="archiefvernietigingscomponent@example.com",
                help_text="The email address to use to send the automatic emails",
                max_length=254,
                verbose_name="from email",
            ),
        ),
    ]
