# Generated by Django 2.2.20 on 2021-11-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0008_auto_20211117_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automaticemail",
            name="type",
            field=models.CharField(
                choices=[
                    ("report_available", "Report available"),
                    ("review_required", "Review required"),
                    ("changes_required", "Changes required"),
                    ("review_reminder", "review_reminder"),
                ],
                help_text="The type of email",
                max_length=200,
                unique=True,
                verbose_name="type",
            ),
        ),
    ]
