# Generated by Django 2.2.12 on 2021-03-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomaticEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("report_available", "Report available"),
                            ("review_required", "Review required"),
                            ("changes_required", "Changes required"),
                        ],
                        help_text="The type of email",
                        max_length=200,
                        unique=True,
                        verbose_name="type",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The text sent in the email body", verbose_name="body"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="The text sent in the email subject",
                        max_length=200,
                        verbose_name="subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automatic email",
                "verbose_name_plural": "Automatic emails",
            },
        ),
    ]
