# Generated by Django 2.2.12 on 2021-03-12 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("action_required", "An action is required"),
                            ("never", "Never"),
                        ],
                        default="action_required",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User associated with the preferences",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email preference",
                "verbose_name_plural": "Email preferences",
            },
        ),
    ]
