# Generated by Django 2.2.18 on 2021-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_auto_20210415_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailpreference",
            name="preference",
            field=models.CharField(
                choices=[
                    ("action_required", "When an action is required"),
                    ("never", "Never"),
                ],
                default="action_required",
                max_length=100,
            ),
        ),
    ]
