# Generated by Django 2.2.12 on 2021-02-18 10:09

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThemeConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        help_text="Image will be scaled down to a height of 100 pixels. Typically upload a picture with a height of 200 pixels.",
                        upload_to="theme/",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        help_text="Shown on the top of the footer.",
                        max_length=100,
                        verbose_name="Organization name",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Shown just below the organization name in the footer.",
                        max_length=200,
                        verbose_name="Tagline",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Shown below the tagline in the footer.",
                        max_length=50,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Shown as an address section at the bottom of the footer. Newlines are supported.",
                        max_length=400,
                        verbose_name="Address",
                    ),
                ),
                (
                    "color_primary",
                    models.CharField(
                        default="04a5bb",
                        help_text="The main color used for footer and buttons.",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[0-9a-fA-F]+"),
                                "Enter a valid HTML color code value consisting of only hexidecimal characters.",
                                "invalid",
                            )
                        ],
                        verbose_name="Primary color",
                    ),
                ),
                (
                    "color_primary_light",
                    models.CharField(
                        default="C3eaef",
                        help_text="Used in places where the main color is too dark.",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[0-9a-fA-F]+"),
                                "Enter a valid HTML color code value consisting of only hexidecimal characters.",
                                "invalid",
                            )
                        ],
                        verbose_name="Primary color (light)",
                    ),
                ),
                (
                    "color_secondary",
                    models.CharField(
                        default="017092",
                        help_text="Typically a darker shade or contrasting color of the primary color, used for button hover states, panel headers and outlines.",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[0-9a-fA-F]+"),
                                "Enter a valid HTML color code value consisting of only hexidecimal characters.",
                                "invalid",
                            )
                        ],
                        verbose_name="Secondary color",
                    ),
                ),
                (
                    "color_link",
                    models.CharField(
                        default="017092",
                        help_text="The main link color.",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[0-9a-fA-F]+"),
                                "Enter a valid HTML color code value consisting of only hexidecimal characters.",
                                "invalid",
                            )
                        ],
                        verbose_name="Link color",
                    ),
                ),
                (
                    "color_link_dark",
                    models.CharField(
                        default="051f31",
                        help_text="Typically a darker share of the link color, used for hover states.",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[0-9a-fA-F]+"),
                                "Enter a valid HTML color code value consisting of only hexidecimal characters.",
                                "invalid",
                            )
                        ],
                        verbose_name="Link color (dark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme configuration",
            },
        ),
    ]
