# Generated by Django 2.2.12 on 2020-07-15 12:30

from django.db import migrations
from django.db.models import F


def forwards(apps, _):
    Role = apps.get_model("accounts", "Role")
    Role.objects.update(order=F("id"))


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_role_order"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
