# Generated by Django 2.2.12 on 2021-02-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_set_role_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ("order",),
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
    ]
