# Generated by Django 2.2.12 on 2020-07-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0006_auto_20200713_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlistitem",
            name="zaak",
            field=models.URLField(
                db_index=True,
                help_text="URL-reference to the ZAAK (in Zaken API), which is planned to be destroyed.",
                verbose_name="zaak",
            ),
        ),
    ]
