# Generated by Django 2.2.12 on 2020-06-16 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("destruction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestructionListAssignee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="order")),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assignee",
                    ),
                ),
                (
                    "destruction_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignees",
                        to="destruction.DestructionList",
                        verbose_name="destruction list",
                    ),
                ),
            ],
            options={
                "verbose_name": "destruction list assignee",
                "verbose_name_plural": "destruction list assignees",
                "unique_together": {("destruction_list", "assignee")},
            },
        ),
    ]
