# Generated by Django 2.2.12 on 2020-06-19 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0002_destructionlistassignee"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archive_date",
                    models.DateField(
                        blank=True,
                        help_text="Only zaken with archiefactiedatum less that this date would be displayed for destruction",
                        null=True,
                        verbose_name="archive date",
                    ),
                ),
            ],
            options={"verbose_name": "archive configuration",},
        ),
        migrations.AlterField(
            model_name="destructionlistassignee",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignee",
            ),
        ),
    ]
