# Generated by Django 2.2.12 on 2020-07-07 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0003_auto_20200619_1000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlist",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="destructionlistreview",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created"
            ),
        ),
    ]
