# Generated by Django 2.2.12 on 2020-07-13 13:50
from django.db import migrations

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0005_auto_20200708_1107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlistitem",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("suggested", "suggested for destruction"),
                    ("removed", "removed from the list during review"),
                    ("processing", "is currently being destroyed"),
                    ("destroyed", "successfully destroyed"),
                    ("failed", "destruction did not succeed"),
                ],
                default="suggested",
                max_length=80,
                protected=True,
                verbose_name="status",
            ),
        ),
    ]
