# Generated by Django 2.2.12 on 2021-02-25 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("destruction", "0008_destructionlistitem_extra_zaak_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestructionListReviewComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Text of the comment to the review",
                        max_length=2000,
                        verbose_name="text",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who added the comment to the review",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destruction.DestructionListReview",
                        verbose_name="destruction list review",
                    ),
                ),
            ],
            options={
                "verbose_name": "destruction list review comment",
                "verbose_name_plural": "destruction list review comments",
            },
        ),
    ]
