# Generated by Django 2.2.12 on 2021-02-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0009_destructionlistreviewcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlistreviewcomment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="destruction.DestructionListReview",
                verbose_name="destruction list review",
            ),
        ),
    ]
