# Generated by Django 2.2.18 on 2021-03-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0013_archiveconfig_short_review_zaaktypes"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardReviewAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Reason for the reviewer to request changes to a list.",
                        max_length=200,
                        verbose_name="reason",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Order in which the reasons are shown to the user.",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "standard review answers",
                "verbose_name_plural": "standard review answers",
            },
        ),
        migrations.AlterField(
            model_name="destructionlistreview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "approved"),
                    ("changes_requested", "changes requested"),
                    ("rejected", "rejected"),
                ],
                max_length=80,
                verbose_name="status",
            ),
        ),
    ]
