# Generated by Django 2.2.18 on 2021-04-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0015_auto_20210326_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="link_to_zac",
            field=models.CharField(
                blank=True,
                help_text="External link to view zaak details. Possible variables to use are: {{ uuid }}, "
                "{{ bronorganisatie }} and {{ identificatie }}. "
                "For example: https://gemeente.lan/mijnzaken/zaak/{{ uuid }}",
                max_length=1000,
                verbose_name="Link to zaakafhandelcomponent",
            ),
        ),
    ]
