# Generated by Django 2.2.18 on 2021-04-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0015_auto_20210326_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="link_to_zac",
            field=models.CharField(
                default="http://example-zac.nl/zaak/{{ uuid }}",
                help_text="Form of the link to a case in a zaakafhandelcomponent, for example: http://myzaken.nl/zaak/{{ uuid }}",
                max_length=1000,
                verbose_name="Link to zaakafhandelcomponent",
            ),
        ),
    ]
