# Generated by Django 2.2.20 on 2021-11-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0017_archiveconfig_days_until_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlistassignee",
            name="assigned_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="assigned on"
            ),
        ),
        migrations.AlterField(
            model_name="destructionlistassignee",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignee",
            ),
        ),
    ]
