# Generated by Django 2.2.20 on 2021-11-15 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0017_archiveconfig_days_until_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlistassignee",
            name="assigned_on",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 11, 15, 12, 5, 48, 619928, tzinfo=utc),
                verbose_name="assigned on",
            ),
        ),
    ]
