# Generated by Django 2.2.20 on 2021-11-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0017_archiveconfig_days_until_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlistassignee",
            name="assigned_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="assigned on"
            ),
        ),
    ]
