# Generated by Django 2.2.20 on 2021-11-15 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0018_destructionlistassignee_assigned_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlistassignee",
            name="assigned_on",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 11, 15, 12, 6, 18, 878210, tzinfo=utc),
                verbose_name="assigned on",
            ),
        ),
    ]
