# Generated by Django 2.2.20 on 2021-11-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destruction', '0018_remove_archiveconfig_days_until_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveconfig',
            name='days_until_expiry',
            field=models.PositiveIntegerField(default=48, help_text='Number of days until an email is sent reminding that the list needs to be dealt with', verbose_name='days until expiry'),
        ),
    ]
