# Generated by Django 2.2.24 on 2021-12-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0018_destructionlistassignee_assigned_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlistassignee",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="reminder sent"),
        ),
    ]
