# Generated by Django 2.2.20 on 2021-11-15 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0019_auto_20211115_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlistassignee",
            name="assigned_on",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 11, 15, 12, 34, 36, 289320, tzinfo=utc),
                verbose_name="assigned on",
            ),
        ),
    ]
