# Generated by Django 2.2.24 on 2021-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0020_auto_20211207_1513"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlist",
            name="zaak_url",
            field=models.URLField(
                blank=True,
                help_text="The URL of the case containing the destruction report for this destruction list.",
                verbose_name="zaak URL",
            ),
        ),
    ]
