# Generated by Django 2.2.20 on 2021-11-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0021_auto_20211115_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlistassignee",
            name="assigned_on",
            field=models.DateTimeField(
                blank=True, default=None, verbose_name="assigned on"
            ),
        ),
    ]
