# Generated by Django 2.2.20 on 2021-11-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0022_auto_20211115_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlistassignee",
            name="assigned_on",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="assigned on"
            ),
        ),
    ]
